SUPABASE_URL = "https://dqhtzvkbgjhnjnmcixcp.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxaHR6dmtiZ2pobmpubWNpeGNwIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NTAxNjAzOCwiZXhwIjoyMDcwNTkyMDM4fQ.VAGtVi21XIXZWRsX0lzfUIZXWZPwWOvkVgaPtPET6R0"
